<?php
/**
 * @file
 * Code for the Accessibots Global Settings feature.
 */

include_once 'abots_global.features.inc';
/**
 * Implements hook_menu_alter().
 */
function abots_global_menu_alter(&$items) {
  // Lock down user login forms to prevent attacks or unsecure logins
  $items['user']['access callback'] = 'user_is_logged_in';
  $items['user/login']['access callback'] = FALSE;
  $items['user/password']['access callback'] = FALSE;
}
